### ISSUE TITLE
Portrait format have control buttons misplaced over the song's cover as compared to README's screenshots

### ISSUE THREAD

**Issue by Porkepix** [enteraname74/SoulSearching#14]
See screenshot below for where the buttons are placed on my phone. This happens whether the song have a cover or not (I just ended up using the same screenshot as the color scheme issue).

<details>
<summary>
Screenshot
</summary>

![Screenshot_20240109-121520](https://github.com/enteraname74/SoulSearching/assets/709500/332004ad-7e3f-48ee-80cd-467718b7fcfe)

</details>

Device details:
Xperia XZ running Android Oreo (8.0) on stock ROM.

**Comment by enteraname74** [comment]
I think that this issue is due to how I manage the disposition of elements on the player view.
I will try the application on screen size like your phone on an emulator.

**Comment by enteraname74** [comment]
The latest version of the app has a better handling of small screens and this issue should not happen again (tested on an emulator with Android 8 and the same phone size as your Xperia XZ (5,2'')). Let me know if it works for you
