### ISSUE TITLE
Landscape mode have the next button much much smaller than the previous and play/pause one

### ISSUE THREAD

**Issue by Porkepix** [enteraname74/SoulSearching#15]
See screenshot below on the difference of size between the buttons

<details>
<summary>
Screenshot
</summary>

![Screenshot_20240109-140506](https://github.com/enteraname74/SoulSearching/assets/709500/408724a6-aa43-4adc-8f02-61e16b7b5064)

</details>

Device details:
Xperia XZ running Android Oreo (8.0) on stock ROM.

EDIT: I'm also unsure if we should see so few or so much at the bottom as we see here.

**Comment by enteraname74** [comment]
Landscape mode has been reworked, on the latest version of the app, to better work on all kind of screen size. I tested it with a phone similar to your Xperia XZ (Android 8.0, size 5,2''). Let met know if it works for you.

**Comment by enteraname74** [comment]
> @enteraname74 On 0.8.0, this is "fixed", indeed the buttons have the same size, but now the whole player on landscape takes like 20% of the screen width and is centered, creating huge margins on every side of the screen.

Could you share a screenshot of this ? The look of the landscape mode of the player has been reworked to ensure that there are no UI glitches but it certainly needs UI enhancement
