### ISSUE TITLE
Add cover to the notification

### ISSUE THREAD

**Issue by Porkepix** [enteraname74/SoulSearching#17]
When the song have a cover, have it displayed in the notification could be a nice improvement.

Note that you can even push dynamic theming to also color the notification: I've seen other players do it. This might be under a preference though as one can dislike this.

**Comment by enteraname74** [comment]
This should be fixed in the latest version of the app. Let me know if it works for you.

**Comment by enteraname74** [comment]
> @enteraname74 It seems to not be the case,  worse it now shows only the name of the application, a permanent "now", the three players buttons on white background and that's all.
> 
> Note it's on release 0.8.0, 0.8.1 isn't yet available on F-droid.

The 0.8.1 fixes some issues where a song metadata would not be shown on notifications below Android 13 (name, artist, cover). This should fix your issue (tested on Android 11 and 8). Let me know if it works when you can test this release 👍
