### ISSUE TITLE
Add notification with playing song information on the lockscreen

### ISSUE THREAD

**Issue by Porkepix** [enteraname74/SoulSearching#19]
The lockscreen could have a notification showing current playing song information and controls to play/pause or go to next/previous, this would be a nice improvement.

**Comment by enteraname74** [comment]
Normally, the notification should be present on the lock screen, but I know that some phone manufacturers like to add things to their version of Android that can restrain some features. It could also be that the system that I use do not work well on Android 8. I will search about it.

Just to be sure, the notification appears when you launch a song?
If it's the case, when you lock your phone, does it appear to the lock screen immediately after?

On some phones, the notification can appear for a few minutes before the system decides to remove it. Normally it's not the case on recent versions of Android, but maybe it differs in Android 8.

**Comment by enteraname74** [comment]
After updating the way the music service work, I have done some tests on Android 8 to be sure that the music notification correctly appears on the lock screen. It should now work properly. Let me know if it works for you.

**Comment by enteraname74** [comment]
> @enteraname74 No there's no notification, still just the background showing song's cover.
> 
> EDIT: Note it's on release 0.8.0, 0.8.1 isn't yet available on F-droid.

I see, the 0.8.1 should improve this as I fixed some issues with notifications on devices below Android 13 (tested on Android 11 and 8). Let me know if you still have issues with the 0.8.1 when you can test it 👍
