### ISSUE TITLE
Notification can get stuck on one song which is not the playing one and not update anymore

### ISSUE THREAD

**Issue by Porkepix** [enteraname74/SoulSearching#20]
While tinkering in the application, I found out the notification shows information about a song which isn't the playing one anymore. Moving to the next/previous song wasn't updating it anymore. I don't know what triggered this and therefore don't have any STR unfortunately.

Device details:
Xperia XZ running Android Oreo (8.0) on stock ROM.

**Comment by enteraname74** [comment]
I think that it may be related to previous issue with the lock screen notification.
I use something called a "service" to manage the player and the notification.

This service can possibly be cancelled by the system, and thus the notification may not be able to be updated correctly.
Normally this problem should not appear, but I'm not really sure if there are some specifications for Android 8.

What I just said is just a supposition, I will have to dig deeper to find what really cause this issue. 
I will inform you if I find something.

**Comment by enteraname74** [comment]
After some tests on Android 8 with the latest version of the app, this should not be a problem anymore. Let me know if it works for you.
